version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: mysql_rachid
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sistema_rachid
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rachid_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rachid_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/sistema_rachid
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - database
    networks:
      - rachid_network

volumes:
  db_data:

networks:
  rachid_network:
